### ISSUE TITLE
[BUG] Config in the Debugger panel are clear between refresh

### ISSUE THREAD

**Issue by daehli** [botpress/studio#216]
I was checking an older version of botpress `12.22.2`. I was playing around with the debugger configuration panel. One of my use cases was to pick a specific user.

In the following video, you can see the userID is already filled and between refresh the user stay in the configuration

## Version 12.22.2
https://user-images.githubusercontent.com/6981314/144500555-b3477292-0d89-4a5d-a5bb-b2125506eaaf.mov

In the most recent version, the UserId is not filled and between refresh, the user is removed 

## Version 12.26.8

https://user-images.githubusercontent.com/6981314/144500799-f23a00b4-0698-494c-a1fc-955fc4ed6fcf.mov

I know some user are using that feature in older version :(

**Comment by laurentlp** [comment]
This is because the _custom_ userId is now stored in the user's attributes (See: https://github.com/botpress/botpress/pull/5591). So instead of fetching the userId from the webchat config, we should try to fetch the user's attributes and look for a `webchatCustomId` key. See [this](https://botpress.com/docs/channels/web#configuring-a-custom-user-id) for reference.
